name: flutter_batch_1
description: Flutter Batch 1 project
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.2

flutter:
  uses-material-design: true
